import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.sun.deploy.util.StringUtils;
import jdk.nashorn.internal.parser.JSONParser;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import com.google.gson.JsonObject;
import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
 if(getRandomQuoteFromAPI() == null){
     System.out.println(getRandomQuoteFromJson());
 }else{System.out.println(getRandomQuoteFromAPI());}

//        System.out.println(getRandomQuoteFromJson());
//        System.out.println(getRandomQuoteFromAPI());

    }

    public static String getRandomQuoteFromJson(){
        try{
            //Create a new Gson object
            Gson gson = new Gson();

            //Read the recentquotes.json file
            BufferedReader reader = new BufferedReader(new FileReader("resources/quotes.json"));

            //convert the json to  Java object (quotes)
            Quote[] quotes = gson.fromJson(reader, Quote[].class);

           //Printing the quotes/authors Details

            //Generating a random number based on array length
            int rand = (int)(Math.random()*(quotes.length));
            //Printing out random quote
            return quotes[rand].toString();
        }catch (IOException e){
            e.printStackTrace();
            return null;
        }

    }

    public static String getRandomQuoteFromAPI(){


        try {

            URL url = new URL("https://ron-swanson-quotes.herokuapp.com/v2/quotes");

            HttpURLConnection con = (HttpURLConnection) url.openConnection();
            con.setRequestMethod("GET");

            BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer content = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
//                System.out.println(inputLine);
                content.append(inputLine);

           // to turn into GSON:
                Gson gson = new Gson();
                APIQuote quote = new APIQuote(inputLine);
                String jsonOfAPIQuotes = gson.toJson(quote);
                APIQuote quoteFromJsonn = gson.fromJson(jsonOfAPIQuotes, APIQuote.class);

            //SAVING
            //
                BufferedWriter writer = null;
                writer = new BufferedWriter(new FileWriter("resources/quotess.json"));
//
                writer.append(jsonOfAPIQuotes);

//                //createa file out of the output stream
//                //save into file path
//                System.out.println("Test"+jsonOfAPIQuotes);


           //SAVING

                return quoteFromJsonn.toString();

            }
            in.close();


        }catch (MalformedURLException e){

        } catch(ProtocolException e){

        }catch(IOException e){
            e.printStackTrace();

        }
        return  getRandomQuoteFromJson();
    }

    public static void savingResponseToJson(){


    }
}

