import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Random;
import java.util.concurrent.ThreadLocalRandom;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

            try{
                //Create a new Gson object
                Gson gson = new Gson();

                //Read the recentquotes.json file
                BufferedReader reader = new BufferedReader(new FileReader("resources/quotes.json"));

                //convert the json to  Java object (quotes)
                Quotes[] quotes = gson.fromJson(reader,Quotes[].class);

                //Printing the quotes/authors Details

                //Generating a random number based on array length
                int rand = (int)(Math.random()*(quotes.length-1));
                //Printing out random quote
                System.out.println(quotes[rand].toString());
            }catch (IOException e){
                e.printStackTrace();
            }
    }

}
